//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.ExpertFinder.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.ExpertFinder.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   情報を入力してください (最大 300 文字) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutMePlaceHolderText {
            get {
                return ResourceManager.GetString("AboutMePlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自己紹介 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutMeTitle {
            get {
                return ResourceManager.GetString("AboutMeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャットを開始する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChatTitle {
            get {
                return ResourceManager.GetString("ChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーワードを入力して、プロファイルにその情報を持つユーザーを検索します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultCardContentME {
            get {
                return ResourceManager.GetString("DefaultCardContentME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   もっと見る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイルの編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditProfileTitle {
            get {
                return ResourceManager.GetString("EditProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自身のプロファイルを更新して、あなたのことを同僚に知らせてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmptyProfileCardContent {
            get {
                return ResourceManager.GetString("EmptyProfileCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問題が発生しました。数分後にもう一度お試しください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   問題が発生したため、プロファイルを更新できませんでした。数分後にもう一度お試しください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToUpdateProfile {
            get {
                return ResourceManager.GetString("FailedToUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このページにアクセスする権限がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ForbiddenErrorMessage {
            get {
                return ResourceManager.GetString("ForbiddenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FullNameTitle {
            get {
                return ResourceManager.GetString("FullNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期しないエラーが発生しました。ページを更新してください。問題が解決しない場合は、管理者にお問い合わせください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイルへ移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GotoProfileTitle {
            get {
                return ResourceManager.GetString("GotoProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   組織内で特定の専門知識と技能を持つユーザーを検索できます。できることは次のとおりです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヒント : 技能 (「データ ビジュアライゼーション」など) 、興味 (「ハイキング」) 、学歴を入力して、プロファイルにその情報を持つ人々を見つけます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitialSearchResultMessageBodyText {
            get {
                return ResourceManager.GetString("InitialSearchResultMessageBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次のことができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitialSearchResultMessageHeaderText {
            get {
                return ResourceManager.GetString("InitialSearchResultMessageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報を入力してください (最大 100 文字) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterestsPlaceHolderText {
            get {
                return ResourceManager.GetString("InterestsPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   興味 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InterestTitle {
            get {
                return ResourceManager.GetString("InterestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたのアカウントはこの組織に所属していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidTenant {
            get {
                return ResourceManager.GetString("InvalidTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サインインに成功しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoginSuccessText {
            get {
                return ResourceManager.GetString("LoginSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大 5 つのユーザー プロファイルを選択できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaxUserProfilesError {
            get {
                return ResourceManager.GetString("MaxUserProfilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイ プロファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MyProfileTitle {
            get {
                return ResourceManager.GetString("MyProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイルが他の人にどのように見えるかを確認します。技能、興味、学歴でプロファイルを更新します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MyProfileWelcomeCardContent {
            get {
                return ResourceManager.GetString("MyProfileWelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoneText {
            get {
                return ResourceManager.GetString("NoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーを検索するには、サインインする必要があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotLoggedInText {
            get {
                return ResourceManager.GetString("NotLoggedInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RefreshLinkText {
            get {
                return ResourceManager.GetString("RefreshLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報を入力してください (最大 200 文字) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SchoolsPlaceHolderText {
            get {
                return ResourceManager.GetString("SchoolsPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   学歴 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SchoolsTitle {
            get {
                return ResourceManager.GetString("SchoolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [検索] をクリックして、技能、興味、学歴でユーザーをフィルタリングします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchCardContent {
            get {
                return ResourceManager.GetString("SearchCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果が見つかりませんでした。別のキーワードをお試しください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchResultNoItemsText {
            get {
                return ResourceManager.GetString("SearchResultNoItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーを検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchTaskModuleTitle {
            get {
                return ResourceManager.GetString("SearchTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索する用語を入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchTextBoxPlaceholder {
            get {
                return ResourceManager.GetString("SearchTextBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   技能、興味、学歴でユーザーをフィルタリングします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchWelcomeCardContent {
            get {
                return ResourceManager.GetString("SearchWelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サインイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SignInButtonText {
            get {
                return ResourceManager.GetString("SignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーを検索するには、サインインする必要があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SignInCardText {
            get {
                return ResourceManager.GetString("SignInCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SIGNOUT;LOGOUT;SIGN OUT;LOG OUT;サインアウト;ログアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SignOutCommandText {
            get {
                return ResourceManager.GetString("SignOutCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サインアウトしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SignOutText {
            get {
                return ResourceManager.GetString("SignOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報を入力してください (最大 100 文字) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SkillsPlaceHolderText {
            get {
                return ResourceManager.GetString("SkillsPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   技能 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SkillsTitle {
            get {
                return ResourceManager.GetString("SkillsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このサービスへのアクセス中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnauthorizedErrorMessage {
            get {
                return ResourceManager.GetString("UnauthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   各項目の間にはセミコロンを使用します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationTaskModuleMessage {
            get {
                return ResourceManager.GetString("ValidationTaskModuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewButtonText {
            get {
                return ResourceManager.GetString("ViewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   組織内で特定の専門知識と技能を持つ人物を検索できます。プロファイルにその情報があれば見つけることができます。できることは次のとおりです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WelcomeCardContent {
            get {
                return ResourceManager.GetString("WelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ようこそ ! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
